<?php

/**
 * @file
 *
 * Module file for the Ting subject list module.
 */

/* Constants */
define('TING_SUBJECT_LIST_PATH', drupal_get_path('module', 'ting_subject_list'));


/**
 * Implements hook_ctools_plugin_directory().
 */
function ting_subject_list_ctools_plugin_directory($owner, $plugin_type) {
	if ($owner == 'ctools' && !empty($plugin_type)) {
		return "plugins/$plugin_type";
	}
}

/**
 * Implements hook_theme().
 */
function ting_subject_list_theme() {
	$common = array(
		'path' => TING_SUBJECT_LIST_PATH . '/theme',
		'file' => 'theme.inc', 
	);
	return array(
		'ting_subject_list' => array(
			'variables' => array(
				'subjects' => array(),
				'column_count' => 3,
			),
			'template' => 'ting-subject-list',
		) + $common,
		'ting_subject_list_column' => array(
			'variables' => array(
				'subjects' => array(),
				'column_title' => NULL,
			),
			'template' => 'ting-subject-list-column',
		) + $common,
		'ting_subject_list_subject' => array(
			'variables' => array(
				'subject' => NULL,
			),
			'template' => 'ting-subject-list-subject',
		) + $common,
	);
}

/**
 * Fetch Ting subjects from the data well, by exploiting the facet search 
 * option on OpenSearch webservice. 
 *
 * @param $query
 *   A cql query string specifying the type of materials to search through.
 * @param $num_resullt
 *   The max number of results to return.
 */
function ting_subject_list_get_subjects($query, $num_results = 100) {
	require_once drupal_get_path('module', 'ting') . '/ting.client.inc';

	$request = ting_get_request_factory()->getSearchRequest();
	$request->setQuery($query);
	if ($agency = variable_get('ting_agency', FALSE)) {
		$request->setAgency($agency);
	}
	$profile = variable_get('ting_search_profile', '');
	if (!empty($profile) && method_exists($request, 'setProfile')) {
	  $request->setProfile($profile);
	}
	// Set defaults
	$request->setStart(1);
	$request->setNumResults(1);
	$request->setFacets(array('facet.subject'));
	// Set the number of subjects to return
	$request->setNumFacets($num_results);

	$search_result = ting_execute($request);
	return $search_result;
}

/**
 * Use OpenScan to retrieve Ting subjects from the data well.
 */
function ting_subject_list_do_scan($lower, $num_results = 60, $min_count = 50) {
	require_once drupal_get_path('module', 'ting') . '/ting.client.inc';
  $request = ting_get_request_factory()->getScanRequest();
  $request->setField('phrase.subject');
  $request->setLower($lower);
  $request = ting_add_agency($request);
  $request->setMinFrequency(1500);
  return ting_execute($request);
}